# Generated by Django 4.2.16 on 2024-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='delete_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
